server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://10.132.54.169:3305/lzy_database?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 741221

jwt:
  secret: a4664280bb05135bdfe79d62078e15347d02440a951896714f4af4e0b7eb2873d1686c1da2da0d048a03673be1e88b1fcea8b9d86a5dc49adbecb14e8b5a5da7